#!/bin/bash

perf stat -o pc_bench_lf_stack_high_no_bs_10it_60m_symmetric_2.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf stack none 1 1 60000000 1 1000 1000
perf stat -o pc_bench_lf_stack_high_no_bs_10it_60m_symmetric_4.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf stack none 2 2 60000000 1 1000 1000
perf stat -o pc_bench_lf_stack_high_no_bs_10it_60m_symmetric_8.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf stack none 4 4 60000000 1 1000 1000
perf stat -o pc_bench_lf_stack_high_no_bs_10it_60m_symmetric_16.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf stack none 8 8 60000000 1 1000 1000
perf stat -o pc_bench_lf_stack_high_no_bs_10it_60m_symmetric_20.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf stack none 10 10 60000000 1 1000 1000

perf stat -o pc_bench_lb_stack_high_no_bs_10it_60m_symmetric_2.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb stack none 1 1 60000000 1 1000 1000
perf stat -o pc_bench_lb_stack_high_no_bs_10it_60m_symmetric_4.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb stack none 2 2 60000000 1 1000 1000
perf stat -o pc_bench_lb_stack_high_no_bs_10it_60m_symmetric_8.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb stack none 4 4 60000000 1 1000 1000
perf stat -o pc_bench_lb_stack_high_no_bs_10it_60m_symmetric_16.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb stack none 8 8 60000000 1 1000 1000
perf stat -o pc_bench_lb_stack_high_no_bs_10it_60m_symmetric_20.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb stack none 10 10 60000000 1 1000 1000

perf stat -o pc_bench_lf_queue_high_no_bs_10it_60m_symmetric_2.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf queue none 1 1 60000000 1 1000 1000
perf stat -o pc_bench_lf_queue_high_no_bs_10it_60m_symmetric_4.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf queue none 2 2 60000000 1 1000 1000
perf stat -o pc_bench_lf_queue_high_no_bs_10it_60m_symmetric_8.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf queue none 4 4 60000000 1 1000 1000
perf stat -o pc_bench_lf_queue_high_no_bs_10it_60m_symmetric_16.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf queue none 8 8 60000000 1 1000 1000
perf stat -o pc_bench_lf_queue_high_no_bs_10it_60m_symmetric_20.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lf queue none 10 10 60000000 1 1000 1000

perf stat -o pc_bench_lb_queue_high_no_bs_10it_60m_symmetric_2.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb queue none 1 1 60000000 1 1000 1000
perf stat -o pc_bench_lb_queue_high_no_bs_10it_60m_symmetric_4.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb queue none 2 2 60000000 1 1000 1000
perf stat -o pc_bench_lb_queue_high_no_bs_10it_60m_symmetric_8.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb queue none 4 4 60000000 1 1000 1000
perf stat -o pc_bench_lb_queue_high_no_bs_10it_60m_symmetric_16.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb queue none 8 8 60000000 1 1000 1000
perf stat -o pc_bench_lb_queue_high_no_bs_10it_60m_symmetric_20.log -r 10 -x, -e task-clock,cycles,instructions,branches,branch-misses,cache-references,cache-misses,L1-dcache-loads,L1-dcache-load-misses,L1-icache-load-misses,L1-dcache-stores,LLC-loads,LLC-load-misses,LLC-stores,LLC-store-misses hwloc-bind node:0 bin/pc-bench lb queue none 10 10 60000000 1 1000 1000
